version: "3.8"

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT}
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
    networks:
      - journey

  postgres:
    image: postgres:16.2-apine3.19
    container_name: journey-api-db
    ports:
      - 5432:5432
    environment:
      postgres_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      postgres_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      postgres_DATABASE_HOST: ${JOURNEY_DATABASE_HOST}
    networks:
      - journey

networks:
  journey:
    driver: bridge
